import { $ } from "bun";
import { readFile, writeFile } from "node:fs/promises";

await $`forge build --silent`;
const artifact = JSON.parse(
  await readFile("out/scanner.sol/AssetScanner.json", "utf8")
) as { deployedBytecode: { object: string } };

const bytecode = artifact.deployedBytecode.object;
if (!bytecode || !bytecode.startsWith("0x") || bytecode.length < 4) {
  throw new Error("forge did not produce deployedBytecode");
}

await writeFile(
  "src/scanner.bytecode.ts",
  `// AUTO-GENERATED by compile.ts. Do not edit by hand.
export const SCANNER_DEPLOYED_BYTECODE = "${bytecode}" as const;
export const SCANNER_ADDRESS = "0x0000000000000000000000000000000000009999" as const;
`
);
console.log(`Wrote src/scanner.bytecode.ts (${(bytecode.length - 2) / 2} bytes)`);
